version: '3'
services:
    web:
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                FPM_IMAGE: bp-fpm
        image: bp-web
        labels:
            - traefik.http.routers.lra-management-web.rule=Host(${APP_DOMAIN})
            - "traefik.http.routers.bp-web.tls.certresolver=lets-encrypt"
            - "traefik.http.routers.bp-web.tls=true"
            - "traefik.http.services.bp-web.loadbalancer.server.port=8080"
        environment:
            FPM_SERVICE: fpm
        ports:
            - "8123:80"
        networks:
            - traefik
            - default
        volumes:
            - "./:/var/www/html"
        depends_on:
            - fpm

    fpm:
        build:
            context: .
            dockerfile: ./docker/fpm/Dockerfile
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_ENABLE: 0
        image: bp-fpm
        user: "${UID:-1000}:${UID:-1000}"
        volumes:
            - "./docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
            - "./:/var/www/html"
        networks:
            - default
        depends_on:
            - database
            - redis
            - websockets

    database:
        image: mariadb:10.10
        ports:
            - "3308:3306"
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${DB_DATABASE:?err}
            MYSQL_USER: ${DB_USERNAME:?err}
            MYSQL_PASSWORD: ${DB_PASSWORD:?err}
        volumes:
            - "database-storage:/var/lib/mysql"

    scheduler:
        image: bp-fpm
        entrypoint: docker-scheduler-entrypoint
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_ENABLE: 0
        user: "${UID:-1000}:${UID:-1000}"
        volumes:
            - "./:/var/www/html"

    queue-default:
        image: bp-fpm
        entrypoint: docker-queue-listen-entrypoint
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_ENABLE: 0
        deploy:
            mode: replicated
            replicas: 6
        user: "${UID:-1000}:${UID:-1000}"
        volumes:
            - "./:/var/www/html"
        depends_on:
            - fpm

    queue-task:
        image: bp-fpm
        entrypoint: sh -c
        environment:
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_ENABLE: 0
        deploy:
            mode: replicated
            replicas: 6
        command:
            - php artisan queue:listen --queue=task
        user: "${UID:-1000}:${UID:-1000}"
        volumes:
            - "./:/var/www/html"
        depends_on:
            - fpm

    redis:
        image: redis

    vite:
        image: node:19-alpine
        working_dir: /home/node/app
        entrypoint: npm run dev
        networks:
            - traefik
        volumes:
            - "./:/home/node/app"
        labels:
            - traefik.http.routers.lra-management-vite.rule=Host(`vite-${APP_DOMAIN}`)
            - "traefik.http.routers.lra-management-vite.tls=true"
            - "traefik.http.routers.lra-management-vite.tls.certresolver=lets-encrypt"
            - "traefik.http.services.lra-management-vite.loadbalancer.server.port=8080"
            - "traefik.http.services.lra-management-vite.loadbalancer.server.scheme=http"

    websockets:
        image: quay.io/soketi/soketi:89604f268623cf799573178a7ba56b7491416bde-16-debian
        environment:
            DEBUG: '0'
            SOKETI_DEFAULT_APP_ID: ${WEBSOCKET_APP_ID}
            SOKETI_DEFAULT_APP_KEY: ${WEBSOCKET_APP_KEY}
            SOKETI_DEFAULT_APP_SECRET: ${WEBSOCKET_APP_SECRET}
        networks:
            - default
            - traefik
        labels:
            - traefik.http.routers.lra-management-soketi.rule=Host(${APP_DOMAIN}) && PathPrefix(`/ws`)
            - "traefik.http.routers.lra-management-soketi.entrypoints=websecure"
            - "traefik.http.routers.lra-management-soketi.tls=true"
            - "traefik.http.services.lra-management-soketi.loadbalancer.server.port=6001"
            - "traefik.http.services.lra-management-soketi.loadbalancer.server.scheme=http"
            - "traefik.http.routers.lra-management-soketi.middlewares=lra-management-soketi-stripprefix"
            - "traefik.http.middlewares.lra-management-soketi-stripprefix.stripprefix.prefixes=/ws"

volumes:
    database-storage:

networks:
    traefik:
        external: true
    default:
        driver: bridge
