version: '3.8'
services:
    fpm:
        build:
            context: .
            dockerfile: ./docker/fpm/Dockerfile
        image: docker.hank-it.com/betterprotect/fpm:${APP_TAG}
        restart: always
        environment:
            APP_KEY: ${APP_KEY:?err}
            ASSET_URL: ${APP_URL}
            APP_URL: ${APP_URL}
            APP_DOMAIN: ${APP_DOMAIN}
            SESSION_SECURE_COOKIE: ${SESSION_SECURE_COOKIE}
            DB_HOST: database
            DB_DATABASE: ${DB_DATABASE:?err}
            DB_USERNAME: ${DB_USERNAME:?err}
            DB_PASSWORD: ${DB_PASSWORD:?err}
            MAIL_DRIVER: ${MAIL_DRIVER}
            MAIL_HOST: ${MAIL_HOST}
            MAIL_PORT: ${MAIL_PORT}
            MAIL_USERNAME: ${MAIL_USERNAME}
            MAIL_PASSWORD: ${MAIL_PASSWORD}
            MAIL_ENCRYPTION: ${MAIL_ENCRYPTION}
            PUSHER_APP_KEY: betterprotect
            PUSHER_APP_SECRET: betterprotect
            PUSHER_APP_ID: betterprotect
            PUSHER_APP_CLUSTER: eu
        volumes:
            - app-storage:/var/www/html/storage
        networks:
            - default

    webserver:
        image: docker.hank-it.com/betterprotect/webserver:${APP_TAG}
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                FPM_IMAGE: docker.hank-it.com/betterprotect/fpm
        restart: always
        networks:
            - default
        volumes:
            - app-storage:/var/www/html/storage
        environment:
            FPM_SERVICE: fpm
            WEBSOCKET_SERVICE: websocket
        ports:
            - "127.0.0.1:8081:80"
        depends_on:
            - database
            - fpm

    queue:
        image: docker.hank-it.com/betterprotect/fpm:${APP_TAG}
        entrypoint: bash -c
        restart: always
        command:
            - php artisan queue:work --tries 3 --timeout 120 database --queue task
        volumes:
            - app-storage:/var/www/html/storage
        depends_on:
            database:
                condition: service_healthy

    websocket:
        image: docker.hank-it.com/betterprotect/fpm:${APP_TAG}
        entrypoint: bash -c
        restart: always
        command:
            - php artisan websocket:serve
        volumes:
            - app-storage:/var/www/html/storage
        depends_on:
            database:
                condition: service_healthy

    database:
        image: mariadb:10.10
        restart: always
        networks:
            - default
        environment:
            MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
            MYSQL_DATABASE: ${DB_DATABASE:?err}
            MYSQL_USER: ${DB_USERNAME:?err}
            MYSQL_PASSWORD: ${DB_PASSWORD:?err}
        volumes:
            - database-storage:/var/lib/mysql

volumes:
    database-storage:
    app-storage:

networks:
    default:
